# `altx_version` -- the generated version header, as a target.
#
# The version is derived from git and written down nowhere. The output file
# records the full commit hash as provenance, so a *stale* hash is not
# cosmetic: it labels a result with a commit that did not produce it.
#
# That is why `configure_file` at configure time is not enough. A configure
# happens once and a build happens after every commit, so the header would be
# right the first time and quietly wrong from the second commit onwards. It is
# therefore regenerated by a custom target on every build, and written through
# `copy_if_different`, so that an unchanged version does not rebuild everything
# that includes it.
#
# It is generated once here as well, so that the header exists for clangd and
# for an IDE that indexes the tree before anything has been built.

include_guard(GLOBAL)

include(GitVersion)

set(ALTX_VERSION_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/GenerateVersionHeader.cmake")
set(ALTX_VERSION_INPUT "${CMAKE_SOURCE_DIR}/src/core/Version.hpp.in")

# Mirrors the source layout, so the include reads `#include "core/Version.hpp"`
# exactly as it will once src/ is on the include path and Version.hpp is one
# header among its neighbours.
set(ALTX_GENERATED_INCLUDE_DIR "${CMAKE_BINARY_DIR}/generated")
set(ALTX_VERSION_HEADER "${ALTX_GENERATED_INCLUDE_DIR}/core/Version.hpp")

set(ALTX_VERSION_COMMAND
    "${CMAKE_COMMAND}"
    "-DALTX_SOURCE_DIR=${CMAKE_SOURCE_DIR}"
    "-DALTX_VERSION_INPUT=${ALTX_VERSION_INPUT}"
    "-DALTX_VERSION_OUTPUT=${ALTX_VERSION_HEADER}"
    -P
    "${ALTX_VERSION_SCRIPT}"
)

execute_process(COMMAND ${ALTX_VERSION_COMMAND} COMMAND_ERROR_IS_FATAL ANY)

# For the configure summary only. The header the compiler sees comes from the
# build step below, which runs later and may well see a different commit.
altx_git_version(
    "${CMAKE_SOURCE_DIR}"
    ALTX_VERSION
    ALTX_GIT_HASH
    ALTX_GIT_DIRTY
)

# Reconfiguring when HEAD moves is what makes the summary above honest, and
# costs nothing: the header itself is regenerated per build regardless. Guarded
# on existence because naming a file that is not there makes the generated
# build system consider itself permanently out of date.
if(EXISTS "${CMAKE_SOURCE_DIR}/.git/HEAD")
    set_property(
        DIRECTORY "${CMAKE_SOURCE_DIR}"
        APPEND
        PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/.git/HEAD"
    )
endif()

# `ALL`, so that a bare `cmake --build` regenerates it even when every target
# asked for is already up to date.
add_custom_target(
    altx_version_header
    ALL
    BYPRODUCTS "${ALTX_VERSION_HEADER}"
    COMMAND ${ALTX_VERSION_COMMAND}
    COMMENT "Deriving the version from git"
    VERBATIM
)

add_library(altx_version INTERFACE)
add_library(altx::version ALIAS altx_version)
target_include_directories(
    altx_version
    INTERFACE "${ALTX_GENERATED_INCLUDE_DIR}"
)

# A target-level dependency on an INTERFACE library is followed transitively in
# its place, so every consumer that links `altx_version` is ordered after the
# generator without having to say so.
add_dependencies(altx_version altx_version_header)
